# Generated by Django 3.2 on 2021-10-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_available_product_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='display',
            new_name='is_active',
        ),
    ]
