# Generated by Django 3.2 on 2021-10-12 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_alter_standcategory_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandCategory',
            new_name='Category',
        ),
    ]
