# Generated by Django 3.2 on 2021-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
