# Generated by Django 3.2 on 2021-10-12 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 12, 5, 47, 8, 305921, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
