# Generated by Django 3.2 on 2021-10-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-pk']},
        ),
    ]
